from dataclasses import dataclass
from datetime import datetime
import sys
import urllib.request
from html.parser import HTMLParser

CODE_LIST_URL="https://www.loc.gov/standards/iso639-2/ISO-639-2_utf-8.txt"


req = urllib.request.Request(CODE_LIST_URL, headers={
    "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0",
    "Accept": "plain",
})

FILE_HEADER = f"""package seahawkradio.cms;
// DO NOT EDIT
// This file was generated by '{sys.argv[0]}' on {datetime.now().isoformat()}

import java.util.Optional;

public record Language(String name, String alpha3, Optional<String> alpha2) {{
    public static final Language[] ALL = new Language[] {{"""

FILE_FOOTER="    };\n}\n"

with urllib.request.urlopen(req) as f:
    print(FILE_HEADER)
    for line in f.read().decode("utf-8-sig").splitlines():
        [alpha3bib, alpha3term, alpha2, name_en_list, name_fr_list] = line.split("|")
        # names could be a ";" separated list, we just use the first name given for simplicity
        name_en = name_en_list.split(";")[0].strip()
        if alpha2:
            alpha2_java = f"Optional.of(\"{alpha2}\")"
        else:
            alpha2_java = "Optional.empty()"
        print(f'        new Language("{name_en}", "{alpha3bib}", {alpha2_java}),')
    print(FILE_FOOTER)
