/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package seahawkradio.cms;

import io.javalin.Javalin;
import io.javalin.http.staticfiles.Location;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Javalin app = Javalin.create(config -> config.addStaticFiles("static", Location.CLASSPATH)).start(8080);
        app.get("/", ctx -> ctx.render("index.jte"));
    }
}
