<!DOCTYPE html>
<html lang="en" dir="ltr" itemscope itemtype="https://schema.org/WebPage" prefix="og:http://ogp.me/ns#">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <title>Seahawk Radio</title>

    <!-- TODO: favicon -->
    <!-- TODO: site metadatadata -->
    <!-- TODO: social media metadatadata -->

    <link rel="preload" href="/main.css" as="style" />
    <link rel="stylesheet" href="/main.css" />
</head>

<body>
    <header>
        <h1>Seahawk Radio</h1>
        <nav>
            <a href="/" rel="noopener noreferrer">Home</a>
        </nav>
        <time></time>
    </header>

    <main></main>

    <footer></footer>
</body>

</html>
