package net.seahawkradio.cms;
// DO NOT EDIT
// This file was generated by './scripts/gen-apple-podcast-categories.py' on 2022-10-06T13:30:37.037219

import java.util.Set;

public record ApplePodcastCategory(String name, Set<String> subcategories) {
    public static final ApplePodcastCategory[] ALL = new ApplePodcastCategory[] {
         new ApplePodcastCategory("Arts", Set.of("Books", "Design", "Fashion & Beauty", "Food", "Performing Arts", "Visual Arts")),
         new ApplePodcastCategory("Business", Set.of("Careers", "Entrepreneurship", "Investing", "Management", "Marketing", "Non-Profit")),
         new ApplePodcastCategory("Comedy", Set.of("Comedy Interviews", "Improv", "Stand-Up")),
         new ApplePodcastCategory("Education", Set.of("Courses", "How To", "Language Learning", "Self-Improvement")),
         new ApplePodcastCategory("Fiction", Set.of("Comedy Fiction", "Drama", "Science Fiction")),
         new ApplePodcastCategory("Government", Set.of()),
         new ApplePodcastCategory("History", Set.of()),
         new ApplePodcastCategory("Health & Fitness", Set.of("Alternative Health", "Fitness", "Medicine", "Mental Health", "Nutrition", "Sexuality")),
         new ApplePodcastCategory("Kids & Family", Set.of("Education for Kids", "Parenting", "Pets & Animals", "Stories for Kids")),
         new ApplePodcastCategory("Leisure", Set.of("Animation & Manga", "Automotive", "Aviation", "Crafts", "Games", "Hobbies", "Home & Garden", "Video Games")),
         new ApplePodcastCategory("Music", Set.of("Music Commentary", "Music History", "Music Interviews")),
         new ApplePodcastCategory("News", Set.of("Business News", "Daily News", "Entertainment News", "News Commentary", "Politics", "Sports News", "Tech News")),
         new ApplePodcastCategory("Religion & Spirituality", Set.of("Buddhism", "Christianity", "Hinduism", "Islam", "Judaism", "Religion", "Spirituality")),
         new ApplePodcastCategory("Science", Set.of("Astronomy", "Chemistry", "Earth Sciences", "Life Sciences", "Mathematics", "Natural Sciences", "Nature", "Physics", "Social Sciences")),
         new ApplePodcastCategory("Society & Culture", Set.of("Documentary", "Personal Journals", "Philosophy", "Places & Travel", "Relationships")),
         new ApplePodcastCategory("Sports", Set.of("Baseball", "Basketball", "Cricket", "Fantasy Sports", "Football", "Golf", "Hockey", "Rugby", "Soccer", "Swimming", "Tennis", "Volleyball", "Wilderness", "Wrestling")),
         new ApplePodcastCategory("Technology", Set.of()),
         new ApplePodcastCategory("True Crime", Set.of()),
         new ApplePodcastCategory("TV & Film", Set.of("After Shows", "Film History", "Film Interviews", "Film Reviews", "TV Reviews")),
    };
}

